version: "3" # composeファイルのバージョン
services: 
    go-tech-blog: # サービス名
        build: . # ビルドに使うDockerfileの場所
        ports:
            - 8080:8080
        tty: true # コンテナの永続化
        volumes:
            - ./:/go-tech-blog # マウントディレクトリ
        depends_on: 
            - mysql # 依存関係 go-tech-blog->mysqlの順で起動

    mysql:
        build: ./mysql/
        volumes:
            # 初期データを投入するSQLが格納されているdir
            - ./mysql/sql:/docker-entrypoint-initdb.d
            # 永続化するときにマウントするdir
            - ./mysql/data:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=goblog
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        